# Generated by Django 3.0.5 on 2021-01-08 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='last_message_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
