# Generated by Django 3.0.5 on 2021-01-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210108_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_message_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
