# Generated by Django 3.0.5 on 2021-01-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210108_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='image',
        ),
    ]
