# Generated by Django 3.0.5 on 2021-01-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210114_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_message_conversation', to='main.Message'),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_message',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_message_group', to='main.Message'),
        ),
    ]
