# Generated by Django 3.0.5 on 2021-04-08 07:20

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210331_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='default-group.png', upload_to=main.models.check_path),
        ),
    ]
